readfromstring : readfromstring.o
	g++ readfromstring.o -ljsoncpp -L../../build/debug/src/lib_json -o readfromstring

readfromstring.o: readFromString.cpp
	g++ -c readFromString.cpp -o readfromstring.o -ljsoncpp -I../../include

clean : 
	rm -r *.o



